### ISSUE TITLE
Glückwunsch zum GitHub Sonderpreis 🎉 

### ISSUE THREAD

**Issue by jonico** [TeamBrot/client#3]
@jacob271 @Sohn123 @rgwohlbold @lill28 herzlichen Glückwunsch zum GitHub Sonderpreis :tada:

![image](https://user-images.githubusercontent.com/1872314/115888217-f6cf8200-a452-11eb-96f5-2b05d3438917.png)

Der Sonderpreis ist wie jedes Jahr GitHub Swag - doch statt wie bis jetzt etwas für das Gewinner-Team auszusuchen, haben wir uns gedacht, ihr könntet euch doch selbst jeweils 2 Items aus https://github.myshopify.com/ aussuchen - und ich sorge dann dafür, dass die zu euch kommen.

Schreibt einfach einen Kommentar mit den Items, die ihr gerne hättet.

:octocat: ❤️

**Comment by jacob271** [comment]
Danke! Für mich wäre ein [Invertocat Crewneck Sweatshirt in M, Farbe Pacific Blue](https://github.myshopify.com/collections/hoodies/products/invertocat-crewneck-sweatshirt?variant=29425813192813) und ein [npm shirt in S, Farbe Weiß](https://github.myshopify.com/collections/shirts/products/npm-shirts?variant=39311789162605) großartig ;-)

**Comment by Sohn123** [comment]
Hallo! ich würde den [Outrun Hoodie in L](https://github.myshopify.com/collections/hoodies/products/outrun-hoodie) und das [Universe 2020 T-Shirt in L](https://github.myshopify.com/collections/shirts/products/universe-2020-t-shirt) auf meine Wunschliste packen :)

**Comment by lill28** [comment]
Vielen Dank! 😄 Ich würde mich sehr über ein [Invertocat 2.0 Shirt (M)](https://github.myshopify.com/collections/shirts/products/invertocat-2-0?variant=84018942) und einen [Octoplush](https://github.myshopify.com/collections/collectibles/products/octoplush) freuen.

**Comment by jonico** [comment]
Alles klar, Bestellung ist getätigt, da aus den USA geschickt wird, kann es ein bisschen dauern. Ich melde mich dann bei euch um die Sachen persönlich zu übergeben.

**Comment by jonico** [comment]
@jacob271, @Sohn123, @rgwohlbold, @lill28: Das Paket mit eurem Swag ist heute bei mir angekommen 🎉 .

Ich könnte es zum Beispiel heute nachmittag (vor 18:00 Uhr) vorbeibringen, wenn ihr mir eine Adresse im Stundentendorf nennt, ansonsten könnte ich morgen oder übermorgen nachmittag das Paket abgeben, sagt Bescheid, was euch am besten passt.

**Comment by Sohn123** [comment]
hi @jonico die Adresse Ist die 152a WG 133 im Studentendorf. Ich bin eigentlich immer da. Einfach klingeln

**Comment by jonico** [comment]
> hi @jonico die Adresse Ist die 152a WG 133 im Studentendorf. Ich bin eigentlich immer da. Einfach klingeln

Dann werde ich mal versuchen in der nächsten Stunde vorbeizukommen.
